url=jdbc:postgresql://${VPS_IP:-localhost}:5432/controlstock_reporting
username=${REPORTING_JDBC_USER}
password=${REPORTING_JDBC_PASSWORD}
changeLogFile=changelog/root.yaml
liquibaseSchemaName=public
