apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    monitoring: "true"
  annotations:
    # Kong Ingress Controller descubre este servicio via KongIngress / Ingress resource
    konghq.com/plugins: jwt,rate-limiting
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
